---
- name: Create ble_keykeeper_dir if it does not exist
  ansible.builtin.file:
    path: "{{ble_keykeeper_dir}}"
    state: directory
    mode: '0755'

- name: Ensure group exists
  ansible.builtin.group:
    name: "{{ ble_keykeeper_group }}"
    state: present

- name: Copy files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ble_keykeeper_dir}}"
    owner: "{{ ble_keykeeper_user }}"
    group: "{{ ble_keykeeper_group }}"
    mode: '0644'
  with_items:
    - "ble_helpers.py"
    - "requirements.txt"
    - "coin.hex"

- name: Install udev rules
  ansible.builtin.copy:
    src: "50-blekeykeeper.rules"
    dest: "/etc/udev/rules.d/"
    owner: root
    group: root
    mode: '0644'
  notify: Force systemd to reread configs

- name: Copy gen_coin executable
  ansible.builtin.copy:
    src: "ble_gen_coin.py"
    dest: "{{ble_keykeeper_dir}}"
    owner: "{{ ble_keykeeper_user }}"
    group: "{{ ble_keykeeper_group }}"
    mode: '0744'

- name: Template main executable
  ansible.builtin.template:
    src: ble_keykeeper.py
    dest: "{{ble_keykeeper_dir}}"
    owner: "{{ ble_keykeeper_user }}"
    group: "{{ ble_keykeeper_group }}"
    mode: '0744'
  notify: Restart ble-keykeeper service

- name: Template service file
  ansible.builtin.template:
    src: ble-keykeeper.service
    dest: /etc/systemd/system
    owner: "{{ ble_keykeeper_user }}"
    group: "{{ ble_keykeeper_group }}"
    mode: '0644'
  notify: Restart ble-keykeeper service

- name: Make sure pip3 is installed
  apt:
    name: python3-pip
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: Install python requirements
  pip:
    requirements: "{{ble_keykeeper_dir}}/requirements.txt"
  notify: Restart ble-keykeeper service
