- name: Force systemd to reread configs
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Restart ble-keykeeper service
  ansible.builtin.systemd:
    state: restarted
    name: ble-keykeeper
    enabled: yes
